version: "3.7"

services:
  app:
    build:
      args:
        user: anonymous
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-app
    container_name: my-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - my-network

  db:
    image: mariadb:latest
    container_name: my-db
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mariadb
    volumes:
      - ./docker-compose/mariadb:/docker-entrypoint-initdb.d
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    container_name: my-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
